branch-defaults:
  capstoneproduction:
    environment: 2017pokemoncapstone-env
  deployment:
    environment: 2017pokemoncapstone-env
environment-defaults:
  2017pokemoncapstone-env:
    branch: null
    repository: null
global:
  application_name: 2017PokemonCapstoneBackend
  default_ec2_keyname: 5lnc0p-2017pokemoncapstonebackend
  default_platform: arn:aws:elasticbeanstalk:us-west-1::platform/Node.js running on
    64bit Amazon Linux/4.4.0
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
